### ISSUE TITLE
implement Crossfade functionality 

### ISSUE THREAD

**Issue by markusschloesser** [markusschloesser/MackieC4_P3#100]
1. needs the assignment A or B in audio tracks and return tracks
2. the actual crossfader on Master track. With vpot ring with cut/boost (like Pan).
3. problem: no space/vpot left in ChanStrip mode

@BilldarBagdar I already reduced the amount of sends to 11, to have a SOLO button, I could reduce further for this. what do you think?

**Comment by BilldarBagdar** [comment]
Are you proposing we use the "Split" button and its 3 linked LEDs for A, B, None "Crossfade Select" in "ChanStrip" mode?  I think I've mentioned that idea out loud here before.

Yes, I've never really understood the general need for mapping 12 sends per channel.  Maybe the original developer was out of ideas and just filled the gap between the "device row" and the 3 or 4 "master" encoders with sends because "What else is there?" or whatever.

Personally, more than 4 Sends seems like a recipe for sonic mush.  Maybe there is a use case I'm not seeing, but IMHO, all the sends after the first 8 can go to any other purpose any time. (and maybe after the first 4 Sends?)

**Comment by markusschloesser** [comment]
> Are you proposing we use the "Split" button and its 3 linked LEDs for A, B, None "Crossfade Select" in "ChanStrip" mode? I think I've mentioned that idea out loud here before

Nope, I am proposing using the vpot left of SOLO. 
If NORMAL or return track, switch between off /a/b, 
If master use vpot rotation with cut /boost as xfade. 

Thought about how to do that when I couldn't sleep last night and will hopefully have some time today to implement 
And reduce amount of sends to 10. 
Objections? 😊

**Comment by markusschloesser** [comment]
Got the actual crossfade on master working, but not yet assigning a or b on audio tracks.

**Comment by markusschloesser** [comment]
cannot get the assignment to work. tried for hours. 
for normal mapping to Live params, one can use 
    vpot_display_text.set_text(self.selected_track.mixer_device.crossfader,'X-Fade') 
    vpot_param = (self.selected_track.mixer_device.crossfader, VPOT_DISPLAY_BOOST_CUT)

which works fine. 
However for the A/B/Off assignment buttons on audio or return tracks using `self.selected_track.mixer_device.crossfade_assignments` this doesn't work and shows the infamous Boost Error
    MidiMap.map_midi_cc_with_feedback_map(int, int, int, int, MapMode, CCFeedbackRule, bool)
did not match C++ signature:
    map_midi_cc_with_feedback_map(unsigned int midi_map_handle, class TPyHandle<class ATimeableValue> parameter, int midi_channel, int controller_number, enum NRemoteMapperTypes::TControllerMapMode map_mode, class NPythonMidiMap::TCCFeedbackRule feedback_rule, bool avoid_takeover, float sensitivity=1.0)

Where it wants a PARAM instead of an INT as the second Argument. (I also had dict or type instead of INT errors all of course wrong)
Now the difference between `self.selected_track.mixer_device.crossfader`, `self.selected_track.mixer_device.volume` etc and `self.selected_track.mixer_device.crossfade_assignments` is that the latter is a class:

        class crossfade_assignments(object):
            def __init__(self, *a, *k):
                pass

            @property
            def A(self):
                pass

            @property
            def B(self):
                pass

            @property
            def NONE(self):
                pass

Lost again (most probably due to lacking basics) 🤔🙄

I pushed to GH

**Comment by markusschloesser** [comment]
I found a M4l device which does the assignment thing (https://maxforlive.com/library/device/2734/xfademap)
Will study it later to see how they are doing it (accessing the live api)
Don't know if you know this, but the underlying Live api is the same for python and m4l

**Comment by markusschloesser** [comment]
I'm still lost
I don't need xfade, so if you want it, I need some help :-)
Basically how do I set the values A,B, None(off)?
Also I thought that if there's no setter, that I can only GET those values?

check https://github.com/markusschloesser/MackieC4_P3/commit/6559b842e0d3a2b93f1896282a064494b7755d99 for current status

**Comment by markusschloesser** [comment]
from 10.1\APC40_MkII\MixerComponent.py

`class ChannelStripComponent(ChannelStripComponentBase):`

    def _on_cf_assign_changed(self):
        if self.is_enabled() and self._crossfade_toggle:
            state = self._track.mixer_device.crossfade_assign if self._track else 1
            value_to_send = None
            if state == 0:
                value_to_send = u'Mixer.Crossfade.A'
            elif state == 1:
                value_to_send = u'Mixer.Crossfade.Off'
            elif state == 2:
                value_to_send = u'Mixer.Crossfade.B'
            self._crossfade_toggle.set_light(value_to_send)

**Comment by markusschloesser** [comment]
i fucking did it! 😁💪😇🎊
sorry for the enthusiasm, but this took me a long time.
currently only the actual assignment switching works (and of course crossfading on master), not yet the displaying of the assignment. Plus I want to do a "reset to 0" for the master crossfader)

**Comment by markusschloesser** [comment]
fully done with latest commit
