### ISSUE TITLE
variable referenced before assignment for total amount tracks (index)

### ISSUE THREAD

**Issue by markusschloesser** [markusschloesser/MackieC4_P3#87]
https://github.com/markusschloesser/MackieC4_P3/blob/d7d358d4609ca330a2cfd2070f3bbdda8746d0cb/wip/MackieC4/EncoderAssignmentHistory.py#L137

**Comment by BilldarBagdar** [comment]
Probably fixed with commit d9ac950 on the C4Modeling branch (for now)
